CREATE TABLE Course (
 CourseId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 CourseAbv VARCHAR(15) NOT NULL,
 CourseName VARCHAR(55) NOT NULL
);

CREATE TABLE Users (
 UserId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 Admin INT NOT NULL DEFAULT 0,
 FName VARCHAR(55) NOT NULL,
 LName VARCHAR(75) NOT NULL,
 Email VARCHAR(100) NOT NULL,
 PasswordHash VARCHAR(500) NOT NULL,
 ProfilePicURL VARCHAR(55)
);

CREATE TABLE Question (
 QuestionId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 UserId INT NOT NULL,
 CourseId INT NOT NULL,
 Title VARCHAR(50) NOT NULL,
 Content VARCHAR(10000) NOT NULL,
 TimeStamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
 Tags VARCHAR(500)
);

CREATE TABLE Answer (
 AnswerId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 UserId INT NOT NULL,
 QuestionId INT NOT NULL,
 Content VARCHAR(10000) NOT NULL,
 TimeStamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE Question ADD FOREIGN KEY (CourseId) REFERENCES Course (CourseId);
ALTER TABLE Question ADD FOREIGN KEY (UserId) REFERENCES Users (UserId);
ALTER TABLE Answer ADD FOREIGN KEY (QuestionId) REFERENCES Question (QuestionId);
ALTER TABLE Answer ADD FOREIGN KEY (UserId) REFERENCES Users (UserId);
ALTER TABLE Users ADD UNIQUE(Email);