INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-1003', 'Programming 1');
INSERT INTO course (CourseAbv, CourseName) VALUES ('COMM-1148', 'Communications for BIT');
INSERT INTO course (CourseAbv, CourseName) VALUES ('COMP-1216', 'Information Systems');
INSERT INTO course (CourseAbv, CourseName) VALUES ('MATH-1028', 'Statistics for BIT');
INSERT INTO course (CourseAbv, CourseName) VALUES ('MATH-1029', 'Math for BIT');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PDEV-1001', 'Professional Development 1');
INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-2005', 'Programming 2');
INSERT INTO course (CourseAbv, CourseName) VALUES ('COMP-1215', 'OO System Analysis');
INSERT INTO course (CourseAbv, CourseName) VALUES ('DBMS-1000', 'Database Management Systems 1');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-1000', 'Network Computing 1');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PDEV-2003', 'Professional Development 2');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WEBD-1000', 'Web Development 1');
INSERT INTO course (CourseAbv, CourseName) VALUES ('COMP-2028', 'OO System Design');
INSERT INTO course (CourseAbv, CourseName) VALUES ('DBMS-2004', 'Database Management Systems 2');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-2005', 'Server Administration');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PDEV-3003', 'Professional Development 3');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WEBD-2006', 'Web Development 2');
INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-3000', 'Programming 3');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-2000', 'Network Computing 2');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PROJ-2006', 'Industry Project');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WRKE-2024', 'Co-Operative Work Experience');
INSERT INTO course (CourseAbv, CourseName) VALUES ('BUSA-2007', 'Business and Management for Information Technology');
INSERT INTO course (CourseAbv, CourseName) VALUES ('BUSA-2008', 'Business Issues');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PDEV-4001', 'Professional Development 4');
INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-2006', 'Application Integration');
INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-2007', 'Mobile Application Development');
INSERT INTO course (CourseAbv, CourseName) VALUES ('ADEV-3001', 'Programming 4');
INSERT INTO course (CourseAbv, CourseName) VALUES ('DBMS-2003', 'Data Warehousing');
INSERT INTO course (CourseAbv, CourseName) VALUES ('DBMS-2005', 'Database Management Systems 3');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-2001', 'Linux/Unix Administration');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-2003', 'Advanced Windows Server');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-2006', 'Network Security');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-3001', 'Network Computing 4');
INSERT INTO course (CourseAbv, CourseName) VALUES ('NTWK-3002', 'Network Computing 3');
INSERT INTO course (CourseAbv, CourseName) VALUES ('PROJ-2009', 'Project Management for Information Technology');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WEBD-2003', 'Web Security');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WEBD-2007', 'Full-Stack Web Development');
INSERT INTO course (CourseAbv, CourseName) VALUES ('WEBD-3001', 'Advanced Server-Side Computing');